CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS projects(id SERIAL PRIMARY KEY,name TEXT NOT NULL,description TEXT,status TEXT DEFAULT 'planning',created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS sites(id SERIAL PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,name TEXT NOT NULL,area_ha NUMERIC(12,2),geometry GEOMETRY(POLYGON,4326) NOT NULL,created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS sites_geometry_gix ON sites USING GIST(geometry);
CREATE TABLE IF NOT EXISTS site_metrics(id SERIAL PRIMARY KEY,site_id INTEGER REFERENCES sites(id) ON DELETE CASCADE,measured_at DATE NOT NULL,carbon_score NUMERIC(5,2),biodiversity_score NUMERIC(5,2),biomass_tonnes NUMERIC(12,2));